title: The Waves of Life
subtitle: "With Jesus"
description: ""
author: Zayra
email: zayra@wavesoflife.blog
baseurl: ""
url: ""
permalink: /:year/:month/:day/:title/

future: true

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

sass:
  sass_dir: assets/css
  style: compressed
